default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: mandylan
  password: pagewood

development:
  <<: *default
  database: wupo

test:
  <<: *default
  database: wupo_test

production:
  <<: *default
  database: wupo
  host: https://wupo-db.fly.dev
  username: mandylan
  password: pagewood