default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: mandylan
  password: pagewood

development:
  <<: *default
  database: wupo-db

test:
  <<: *default
  database: wupo_test

production:
  <<: *default
  database: wupo-db
  host: wupo-db.fly.dev
  username: mandylan
  password: pagewood